const portfolioData = {
  domains: [
    {
      id: "multimodal",
      label: "Multimodal",
      heroTitle: "Multimodal",
      heroLine: "Text, audio and vision systems",
      title: "Text, audio, and vision systems",
      summary: "Experiments across text understanding, audio representations, speech signals, fixed-class vision, open-vocabulary detection, and deployment-aware edge vision.",
      signals: ["Text", "Audio", "Speech", "Vision", "YOLOv8", "OWL-ViT", "WavLM", "TFLite"]
    },
    {
      id: "runtime",
      label: "Runtime AI",
      heroTitle: "Runtime AI",
      heroLine: "Offline intelligence for device control",
      title: "Resource-constrained intelligence for device control",
      summary: "Offline and edge-first runtime ideas for smart devices, natural-language commands, local device control, embedded inference constraints, and reliable action layers.",
      signals: ["Offline AI", "Runtime", "Voice control", "Intent", "Device action", "Edge inference"]
    },
    {
      id: "edge-ai",
      label: "Edge AI",
      heroTitle: "Edge AI",
      heroLine: "AI under real hardware constraints",
      title: "Small models and embedded intelligence under hardware limits",
      summary: "Compact NLP, audio acquisition, model-size tradeoffs, quantization thinking, memory limits, and deployment paths for constrained microcontrollers, processors, and edge hardware.",
      signals: ["Tiny NLP", "MiniLM", "MCU", "Memory limits", "Audio acquisition", "Quantization"]
    },
    {
      id: "sensor-platforms",
      label: "Sensor Platforms",
      heroTitle: "Sensor Platforms",
      heroLine: "Physical signals to data systems",
      title: "Sensor data pipelines and embedded electronics foundations",
      summary: "Physical sensing, embedded acquisition, MQTT, AWS IoT ingestion, telemetry structure, RF electronics, hardware validation, and automotive RKE/PKE engineering background.",
      signals: ["Sensors", "Telemetry", "MQTT", "AWS IoT", "RF", "Embedded electronics", "Validation"]
    }
  ],
  projects: [
    {
      id: "offline-runtime-smart-home",
      domain: "runtime",
      name: "Offline Edge AI Runtime / Voice-Controlled Smart Home",
      category: "Prototype / architecture exploration",
      icon: "RT",
      tags: ["Edge AI", "Runtime", "Voice", "Device control"],
      line: "A resource-constrained AI pipeline that turns natural-language device commands into local device actions.",
      objective: "Explore how useful AI behavior can run close to the device instead of depending on a full cloud loop for every command. The objective is voice to intent to device action under memory, latency, and reliability constraints.",
      architecture: ["Voice command", "Local processing", "Intent representation", "Device controller", "Embedded runtime", "Device action"],
      implementation: "The system is structured around a narrow action space, command parsing, an intent representation, and a local device-control layer. The runtime boundary is treated as a product surface: model output must become predictable, testable machine behavior.",
      technologies: ["Embedded runtime concept", "Voice-command pipeline", "Intent representation", "Local inference", "Device-control logic", "Resource-constrained design"],
      challenge: "The difficult part is not just running a model. It is making the model useful inside a constrained runtime where latency, memory, and predictable device action matter.",
      learned: "Resource-constrained AI becomes interesting when the system design is forced to separate language understanding from safe, deterministic device control.",
      future: "Extend the runtime toward multiple device classes with reusable command schemas and local context management."
    },
    {
      id: "tiny-nlp-controller",
      domain: "edge-ai",
      name: "Tiny NLP Model for Embedded Device Control",
      category: "Experiment",
      icon: "NL",
      tags: ["MiniLM", "Intent", "Entities", "Tiny NLP"],
      line: "A compact NLP experiment for turning short device commands into structured intents and entities.",
      objective: "Investigate whether a small language model pipeline can understand constrained device commands without requiring a heavyweight cloud LLM for every interaction.",
      architecture: ["Command text", "Tokenizer", "Compact NLP model", "Intent/entity prediction", "Structured command", "Device layer"],
      implementation: "The experiment focuses on tokenization, compact representation learning, intent labels, entity extraction, training/evaluation tradeoffs, and output formats that can be consumed by embedded device logic.",
      technologies: ["MiniLM experimentation", "Tokenization", "Intent classification", "Entity extraction", "Structured commands", "Model-size evaluation"],
      challenge: "The core tension is balancing useful language understanding against model size, memory pressure, latency, and predictable output behavior.",
      learned: "Small models can be practical when the action space is constrained and the interface between model and device is designed carefully.",
      future: "Compare compact model behavior with hybrid rule/model approaches before considering constrained embedded deployment."
    },
    {
      id: "voice-command-interface",
      domain: "runtime",
      name: "Voice Command Device Interface",
      category: "Prototype / architecture study",
      icon: "VT",
      tags: ["Voice", "Shared commands", "Device UI"],
      line: "A voice-command control layer where natural language becomes the same structured device command representation.",
      objective: "Design a common control architecture where multiple voice commands can drive predictable underlying device behavior.",
      architecture: ["Voice input", "Command representation", "Device action", "Command confirmation", "Device action"],
      implementation: "Voice commands are normalized into a shared command representation before reaching the device layer. The device layer receives structured actions instead of raw natural language.",
      technologies: ["Voice interface", "Command schema", "Device-control layer", "voice interface design"],
      challenge: "The challenge is keeping interaction natural-language input flexible while keeping the final device action deterministic.",
      learned: "Voice-controlled systems become safer and cleaner when model output converges into a single control contract before reaching the device layer.",
      future: "Add richer context so the command representation can include state, user preference, and sensor input."
    },
    {
      id: "aws-iot-sensor-platform",
      domain: "sensor-platforms",
      name: "AWS IoT Sensor Platform",
      category: "Architecture study",
      icon: "IoT",
      tags: ["Sensors", "MQTT", "AWS IoT", "Telemetry"],
      line: "A device-to-cloud sensor-data pipeline from physical acquisition to structured telemetry ingestion.",
      objective: "Connect physical sensor acquisition to a cloud ingestion path while keeping the data format structured and useful for monitoring, automation, or downstream analytics.",
      architecture: ["Sensor", "Embedded device", "MQTT", "AWS IoT", "Data platform"],
      implementation: "The system frames a sensor as a telemetry source, an embedded device as the acquisition and publishing node, MQTT as the transport, and AWS IoT as the managed ingestion layer.",
      technologies: ["Physical sensors", "Embedded acquisition", "MQTT", "AWS IoT", "Structured telemetry", "Cloud ingestion"],
      challenge: "Reliability, identity, certificates, message structure, and network constraints matter as much as the sensor reading itself.",
      learned: "Good IoT platforms start with disciplined telemetry design, not dashboards.",
      future: "Add fleet-style device identity, alert rules, and event-driven processing."
    },
    {
      id: "max9814-audio",
      domain: "edge-ai",
      name: "MAX9814 Audio Acquisition / Edge Audio",
      category: "Multimodal + Edge AI",
      icon: "AU",
      tags: ["MAX9814", "Audio", "ADC", "Signal path"],
      line: "A microphone/audio acquisition experiment for future edge-audio and AI pipelines.",
      objective: "Understand the signal-acquisition side of audio-first intelligent devices before the audio reaches an AI model.",
      architecture: ["Microphone", "MAX9814", "ADC", "Audio samples", "Preprocessing", "Edge AI pipeline"],
      implementation: "The work focuses on microphone gain behavior, analog signal characteristics, ADC sampling, buffering assumptions, and the quality requirements of downstream audio inference.",
      technologies: ["MAX9814 microphone amplifier", "ADC sampling", "Audio buffers", "Signal acquisition", "Preprocessing", "Embedded audio"],
      challenge: "Small audio systems are sensitive to noise, gain, timing, and sampling quality, all before any model is involved.",
      learned: "Audio AI depends heavily on front-end engineering; model quality cannot compensate for a weak acquisition path.",
      future: "Connect the acquisition path to wake-word, speech-embedding, or intent-recognition experiments."
    },
    {
      id: "ravdess-wavlm",
      domain: "multimodal",
      name: "RAVDESS + WavLM Speech AI",
      category: "AI research experiment",
      icon: "SP",
      tags: ["RAVDESS", "WavLM", "Speech", "Embeddings"],
      line: "A speech-representation experiment using WavLM embeddings on the RAVDESS dataset.",
      objective: "Test whether learned speech representations contain useful information for downstream emotion-related classification and richer audio understanding.",
      architecture: ["Audio sample", "WavLM", "Speech embedding", "Downstream classifier", "Evaluation"],
      implementation: "The experiment treats WavLM as a representation extractor, then evaluates whether the resulting embeddings support downstream classification on RAVDESS-style speech samples.",
      technologies: ["RAVDESS dataset", "WavLM", "Audio embeddings", "Representation learning", "Classification evaluation"],
      challenge: "Speech emotion datasets can be small, acted, and ambiguous, so the evaluation must be treated as research exploration rather than a production product.",
      learned: "Speech contains useful signals beyond transcription, but downstream use requires careful dataset and evaluation discipline.",
      future: "Compare embeddings across speech models and study how audio context could support multimodal device interaction."
    },
    {
      id: "vision-yolo-owlvit",
      domain: "multimodal",
      name: "YOLOv8 / OWL-ViT Computer Vision",
      category: "Computer vision experiment",
      icon: "CV",
      tags: ["YOLOv8", "OWL-ViT", "Detection", "Open vocabulary"],
      line: "Object-detection experiments comparing fixed-class and open-vocabulary vision behavior.",
      objective: "Explore modern perception pipelines and understand the difference between trained fixed-class detection and prompt-driven open-vocabulary detection.",
      architecture: ["Image/frame", "YOLOv8 fixed classes", "OWL-ViT text query", "Detections", "Decision layer"],
      implementation: "YOLOv8 represents the fixed-class detection path, while OWL-ViT represents open-vocabulary detection guided by text queries. The project studies how both approaches produce detections that can feed higher-level logic.",
      technologies: ["YOLOv8", "OWL-ViT", "Object detection", "Vision-language models", "Confidence thresholds", "Perception pipeline"],
      challenge: "Fixed-class models can be efficient and precise inside their label set, while open-vocabulary models are more flexible but require careful prompting and thresholding.",
      learned: "Perception becomes useful when detections are connected to decisions, actions, or user-facing workflows.",
      future: "Combine visual detection with device context and multimodal commands."
    },
    {
      id: "food101-tflite",
      domain: "multimodal",
      name: "Calorie Detector - Food-101 to TFLite Edge Vision",
      category: "Computer vision experiment",
      icon: "F1",
      tags: ["Food-101", "TFLite", "Classification", "Edge vision"],
      line: "A dataset-to-deployment vision pipeline for food classification and mobile/edge inference.",
      objective: "Explore the complete path from dataset selection to model training, evaluation, conversion, and deployment-oriented inference.",
      architecture: ["Food-101 dataset", "Model training", "Evaluation", "TFLite conversion", "Mobile/edge inference"],
      implementation: "The work frames food recognition as an image-classification problem and follows the deployment path toward TensorFlow Lite so model behavior can be evaluated outside a notebook.",
      technologies: ["Food-101", "Image classification", "Model training", "TensorFlow Lite", "Mobile inference", "Edge vision"],
      challenge: "The gap between a trained model and a deployable model includes size, latency, confidence behavior, and real-world image variation.",
      learned: "Deployment constraints change how model quality should be judged.",
      future: "Improve calibration, test quantization, and connect recognition output to a lightweight nutrition-estimation workflow."
    },
    {
      id: "rke-pke",
      domain: "sensor-platforms",
      name: "RKE / PKE Development",
      category: "Automotive electronics background",
      icon: "RF",
      tags: ["RKE", "PKE", "RF", "Embedded validation"],
      line: "Automotive electronics work around Remote Keyless Entry, Passive Keyless Entry, RF circuitry, and validation.",
      objective: "Represent deeper electronics and embedded-systems background outside AI/ML, especially automotive access systems and RF-oriented development.",
      architecture: ["RF circuitry", "Embedded firmware", "Hardware validation", "RF measurement", "Automotive electronics"],
      implementation: "The work relates to RKE/PKE system behavior, RF circuitry, embedded development, measurement, tuning, validation, and practical automotive electronics constraints.",
      technologies: ["Remote Keyless Entry", "Passive Keyless Entry", "RF circuitry", "Embedded development", "Hardware validation", "RF measurement"],
      challenge: "Automotive electronics requires disciplined validation because RF behavior, hardware tolerances, and system reliability directly affect product behavior.",
      learned: "Strong embedded-AI work benefits from real electronics experience, especially where sensing, firmware, and hardware behavior meet.",
      future: "Use this background to evaluate embedded AI systems with stronger hardware and validation discipline."
    }
  ]
};



